services:
  - type: web
    name: jalai-backend
    runtime: java
    rootDir: backend/jalai-backend
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/jalai-backend-*.jar
    plan: free
    env: java
    javaVersion: 17
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,https://jalai-ecommerce-donation-platform.vercel.app,https://jalai-frontend.onrender.com"
    healthCheckPath: /actuator/health

  # Optional: Add database service
  # - type: pserv
  #   name: jalai-database
  #   runtime: postgresql
  #   plan: free
  #   env: postgresql
